const chai = require('chai');
const expect = chai.expect;

const monobitTest = require('./monobit-test');
const longRunTest = require('./long-run-test');
const pokerTest = require('./poker-test');
const runsTest = require('./runs-test');

const binarySequenceWithHex = require('./PRNGs/hex-prng');
const binarySequenceWithRand = require('./PRNGs/bin-prng');
const binarySequenceLCG = require('./PRNGs/lcg-prng');
const binarySequenceWithLCG = binarySequenceLCG(16253, 20000);
const binarySequenceLFSR = require('./PRNGs/lfsr-prng');
const binarySequenceWithLFSR = binarySequenceLFSR(0b10101000001010101, 20000);

function testKey(key) {
    // console.log('monobitTest', monobitTest(key));
    // console.log('longRunTest', longRunTest(key));
    // console.log('pokerTest', pokerTest(key));
    // console.log('runsTest', runsTest(key));
    return Boolean(monobitTest(key) & longRunTest(key) & pokerTest(key) & runsTest(key));
}

describe('Testing keys generated by different PRNGs', function() {
    it('should pass all fips-140-3 tests for the PRN generated using rand() and hex', function() {
        expect(testKey(binarySequenceWithHex)).to.be.true;
    });

    it('should pass all fips-140-3 tests for the PRN generated using built-in rand() and round()', function() {
        expect(testKey(binarySequenceWithRand)).to.be.true;
    });

    it('should pass all fips-140-3 tests for the PRN generated using LCG PRNG', function() {
        expect(testKey(binarySequenceWithLCG)).to.be.true;
    });

    it('should pass all fips-140-3 tests for the PRN generated using LFSR PRNG', function() {
        expect(testKey(binarySequenceWithLFSR)).to.be.true;
    });
});
